// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	contracts "github.com/eduardtungatarov/goph-keeper/internal/server/contracts"
	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, in, opts
func (_m *Client) Create(ctx context.Context, in *contracts.CreateRequest, opts ...grpc.CallOption) (*contracts.CreateResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *contracts.CreateResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *contracts.CreateRequest, ...grpc.CallOption) (*contracts.CreateResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *contracts.CreateRequest, ...grpc.CallOption) *contracts.CreateResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*contracts.CreateResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *contracts.CreateRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, in, opts
func (_m *Client) Delete(ctx context.Context, in *contracts.DeleteRequest, opts ...grpc.CallOption) (*contracts.DeleteResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *contracts.DeleteResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *contracts.DeleteRequest, ...grpc.CallOption) (*contracts.DeleteResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *contracts.DeleteRequest, ...grpc.CallOption) *contracts.DeleteResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*contracts.DeleteResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *contracts.DeleteRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, in, opts
func (_m *Client) List(ctx context.Context, in *contracts.ListRequest, opts ...grpc.CallOption) (*contracts.ListResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *contracts.ListResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *contracts.ListRequest, ...grpc.CallOption) (*contracts.ListResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *contracts.ListRequest, ...grpc.CallOption) *contracts.ListResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*contracts.ListResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *contracts.ListRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Login provides a mock function with given fields: ctx, in, opts
func (_m *Client) Login(ctx context.Context, in *contracts.LoginRequest, opts ...grpc.CallOption) (*contracts.LoginResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *contracts.LoginResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *contracts.LoginRequest, ...grpc.CallOption) (*contracts.LoginResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *contracts.LoginRequest, ...grpc.CallOption) *contracts.LoginResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*contracts.LoginResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *contracts.LoginRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Read provides a mock function with given fields: ctx, in, opts
func (_m *Client) Read(ctx context.Context, in *contracts.ReadRequest, opts ...grpc.CallOption) (*contracts.ReadResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 *contracts.ReadResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *contracts.ReadRequest, ...grpc.CallOption) (*contracts.ReadResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *contracts.ReadRequest, ...grpc.CallOption) *contracts.ReadResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*contracts.ReadResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *contracts.ReadRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: ctx, in, opts
func (_m *Client) Register(ctx context.Context, in *contracts.LoginRequest, opts ...grpc.CallOption) (*contracts.LoginResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *contracts.LoginResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *contracts.LoginRequest, ...grpc.CallOption) (*contracts.LoginResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *contracts.LoginRequest, ...grpc.CallOption) *contracts.LoginResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*contracts.LoginResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *contracts.LoginRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
