// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	queries "github.com/eduardtungatarov/goph-keeper/internal/server/repository/user/queries"
	mock "github.com/stretchr/testify/mock"
)

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

// FindUserByLogin provides a mock function with given fields: ctx, login
func (_m *UserRepository) FindUserByLogin(ctx context.Context, login string) (queries.User, error) {
	ret := _m.Called(ctx, login)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByLogin")
	}

	var r0 queries.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (queries.User, error)); ok {
		return rf(ctx, login)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) queries.User); ok {
		r0 = rf(ctx, login)
	} else {
		r0 = ret.Get(0).(queries.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, login)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveUser provides a mock function with given fields: ctx, user
func (_m *UserRepository) SaveUser(ctx context.Context, user queries.User) (queries.User, error) {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for SaveUser")
	}

	var r0 queries.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, queries.User) (queries.User, error)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, queries.User) queries.User); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Get(0).(queries.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, queries.User) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserRepository creates a new instance of UserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepository {
	mock := &UserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
