// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: contracts/server/server.proto

package contracts

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExampleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExampleRequest) Reset() {
	*x = ExampleRequest{}
	mi := &file_contracts_server_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExampleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExampleRequest) ProtoMessage() {}

func (x *ExampleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_server_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExampleRequest.ProtoReflect.Descriptor instead.
func (*ExampleRequest) Descriptor() ([]byte, []int) {
	return file_contracts_server_server_proto_rawDescGZIP(), []int{0}
}

func (x *ExampleRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ExampleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExampleResponse) Reset() {
	*x = ExampleResponse{}
	mi := &file_contracts_server_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExampleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExampleResponse) ProtoMessage() {}

func (x *ExampleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_server_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExampleResponse.ProtoReflect.Descriptor instead.
func (*ExampleResponse) Descriptor() ([]byte, []int) {
	return file_contracts_server_server_proto_rawDescGZIP(), []int{1}
}

func (x *ExampleResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_contracts_server_server_proto protoreflect.FileDescriptor

const file_contracts_server_server_proto_rawDesc = "" +
	"\n" +
	"\x1dcontracts/server/server.proto\x12\x06server\"\"\n" +
	"\x0eExampleRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\")\n" +
	"\x0fExampleResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result2K\n" +
	"\rKeeperService\x12:\n" +
	"\aExample\x12\x16.server.ExampleRequest\x1a\x17.server.ExampleResponseB\x1cZ\x1ainternal/server/contracts/b\x06proto3"

var (
	file_contracts_server_server_proto_rawDescOnce sync.Once
	file_contracts_server_server_proto_rawDescData []byte
)

func file_contracts_server_server_proto_rawDescGZIP() []byte {
	file_contracts_server_server_proto_rawDescOnce.Do(func() {
		file_contracts_server_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contracts_server_server_proto_rawDesc), len(file_contracts_server_server_proto_rawDesc)))
	})
	return file_contracts_server_server_proto_rawDescData
}

var file_contracts_server_server_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_contracts_server_server_proto_goTypes = []any{
	(*ExampleRequest)(nil),  // 0: server.ExampleRequest
	(*ExampleResponse)(nil), // 1: server.ExampleResponse
}
var file_contracts_server_server_proto_depIdxs = []int32{
	0, // 0: server.KeeperService.Example:input_type -> server.ExampleRequest
	1, // 1: server.KeeperService.Example:output_type -> server.ExampleResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_contracts_server_server_proto_init() }
func file_contracts_server_server_proto_init() {
	if File_contracts_server_server_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contracts_server_server_proto_rawDesc), len(file_contracts_server_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contracts_server_server_proto_goTypes,
		DependencyIndexes: file_contracts_server_server_proto_depIdxs,
		MessageInfos:      file_contracts_server_server_proto_msgTypes,
	}.Build()
	File_contracts_server_server_proto = out.File
	file_contracts_server_server_proto_goTypes = nil
	file_contracts_server_server_proto_depIdxs = nil
}
