// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"context"
)

type Querier interface {
	//FindUserByLogin
	//
	//  SELECT id, login, password FROM users
	//  WHERE login = $1 LIMIT 1
	FindUserByLogin(ctx context.Context, db DBTX, login string) (User, error)
	//SaveUser
	//
	//  INSERT INTO users (login, password)
	//  VALUES ($1, $2)
	//  RETURNING id, login, password
	SaveUser(ctx context.Context, db DBTX, arg SaveUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
