// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: data.sql

package queries

import (
	"context"
)

const DeleteDataByUserIDAndID = `-- name: DeleteDataByUserIDAndID :execrows
DELETE FROM data
WHERE user_id = $1 AND id = $2
`

type DeleteDataByUserIDAndIDParams struct {
	UserID int64
	ID     int64
}

// DeleteDataByUserIDAndID
//
//	DELETE FROM data
//	WHERE user_id = $1 AND id = $2
func (q *Queries) DeleteDataByUserIDAndID(ctx context.Context, db DBTX, arg DeleteDataByUserIDAndIDParams) (int64, error) {
	result, err := db.ExecContext(ctx, DeleteDataByUserIDAndID, arg.UserID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const FindDataByUserIDAndID = `-- name: FindDataByUserIDAndID :one
SELECT id, user_id, title, type, data FROM data
WHERE user_id = $1 and id = $2
LIMIT 1
`

type FindDataByUserIDAndIDParams struct {
	UserID int64
	ID     int64
}

// FindDataByUserIDAndID
//
//	SELECT id, user_id, title, type, data FROM data
//	WHERE user_id = $1 and id = $2
//	LIMIT 1
func (q *Queries) FindDataByUserIDAndID(ctx context.Context, db DBTX, arg FindDataByUserIDAndIDParams) (Datum, error) {
	row := db.QueryRowContext(ctx, FindDataByUserIDAndID, arg.UserID, arg.ID)
	var i Datum
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Type,
		&i.Data,
	)
	return i, err
}

const SaveData = `-- name: SaveData :one
INSERT INTO data (user_id, title, type, data)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, title, type, data
`

type SaveDataParams struct {
	UserID int64
	Title  string
	Type   string
	Data   []byte
}

// SaveData
//
//	INSERT INTO data (user_id, title, type, data)
//	VALUES ($1, $2, $3, $4)
//	RETURNING id, user_id, title, type, data
func (q *Queries) SaveData(ctx context.Context, db DBTX, arg SaveDataParams) (Datum, error) {
	row := db.QueryRowContext(ctx, SaveData,
		arg.UserID,
		arg.Title,
		arg.Type,
		arg.Data,
	)
	var i Datum
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Type,
		&i.Data,
	)
	return i, err
}
