// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: data.sql

package queries

import (
	"context"
)

const SaveData = `-- name: SaveData :one
INSERT INTO data (user_id, title, type, data)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, title, type, data
`

type SaveDataParams struct {
	UserID int64
	Title  string
	Type   string
	Data   []byte
}

// SaveData
//
//	INSERT INTO data (user_id, title, type, data)
//	VALUES ($1, $2, $3, $4)
//	RETURNING id, user_id, title, type, data
func (q *Queries) SaveData(ctx context.Context, db DBTX, arg SaveDataParams) (Datum, error) {
	row := db.QueryRowContext(ctx, SaveData,
		arg.UserID,
		arg.Title,
		arg.Type,
		arg.Data,
	)
	var i Datum
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Type,
		&i.Data,
	)
	return i, err
}
