// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"context"
)

type Querier interface {
	//SaveData
	//
	//  INSERT INTO data (user_id, title, type, data)
	//  VALUES ($1, $2, $3, $4)
	//  RETURNING id, user_id, title, type, data
	SaveData(ctx context.Context, db DBTX, arg SaveDataParams) (Datum, error)
}

var _ Querier = (*Queries)(nil)
