// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"context"
)

type Querier interface {
	//FindDataByUserIDAndID
	//
	//  SELECT id, user_id, title, type, data FROM data
	//  WHERE user_id = $1 and id = $2
	//  LIMIT 1
	FindDataByUserIDAndID(ctx context.Context, db DBTX, arg FindDataByUserIDAndIDParams) (Datum, error)
	//SaveData
	//
	//  INSERT INTO data (user_id, title, type, data)
	//  VALUES ($1, $2, $3, $4)
	//  RETURNING id, user_id, title, type, data
	SaveData(ctx context.Context, db DBTX, arg SaveDataParams) (Datum, error)
}

var _ Querier = (*Queries)(nil)
