// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/eduardtungatarov/goph-keeper/internal/server/service/data/dto"

	mock "github.com/stretchr/testify/mock"

	queries "github.com/eduardtungatarov/goph-keeper/internal/server/repository/data/queries"
)

// DataService is an autogenerated mock type for the DataService type
type DataService struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, create
func (_m *DataService) Create(ctx context.Context, create dto.Create) error {
	ret := _m.Called(ctx, create)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.Create) error); ok {
		r0 = rf(ctx, create)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, read
func (_m *DataService) Delete(ctx context.Context, read dto.Delete) error {
	ret := _m.Called(ctx, read)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.Delete) error); ok {
		r0 = rf(ctx, read)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// List provides a mock function with given fields: ctx
func (_m *DataService) List(ctx context.Context) ([]queries.Datum, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []queries.Datum
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]queries.Datum, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []queries.Datum); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]queries.Datum)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Read provides a mock function with given fields: ctx, create
func (_m *DataService) Read(ctx context.Context, create dto.Read) (dto.ReadResult, error) {
	ret := _m.Called(ctx, create)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 dto.ReadResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.Read) (dto.ReadResult, error)); ok {
		return rf(ctx, create)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.Read) dto.ReadResult); ok {
		r0 = rf(ctx, create)
	} else {
		r0 = ret.Get(0).(dto.ReadResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.Read) error); ok {
		r1 = rf(ctx, create)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewDataService creates a new instance of DataService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDataService(t interface {
	mock.TestingT
	Cleanup(func())
}) *DataService {
	mock := &DataService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
