// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	queries "github.com/eduardtungatarov/goph-keeper/internal/server/repository/data/queries"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// DeleteByUserIDAndID provides a mock function with given fields: ctx, userID, id
func (_m *Repository) DeleteByUserIDAndID(ctx context.Context, userID int, id int) error {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByUserIDAndID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByUserIDAndID provides a mock function with given fields: ctx, userID, id
func (_m *Repository) GetByUserIDAndID(ctx context.Context, userID int, id int) (queries.Datum, error) {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserIDAndID")
	}

	var r0 queries.Datum
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) (queries.Datum, error)); ok {
		return rf(ctx, userID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) queries.Datum); ok {
		r0 = rf(ctx, userID, id)
	} else {
		r0 = ret.Get(0).(queries.Datum)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, userID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListByUserID provides a mock function with given fields: ctx, userID
func (_m *Repository) ListByUserID(ctx context.Context, userID int) ([]queries.Datum, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListByUserID")
	}

	var r0 []queries.Datum
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]queries.Datum, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []queries.Datum); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]queries.Datum)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: ctx, _a1
func (_m *Repository) Save(ctx context.Context, _a1 queries.Datum) (queries.Datum, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 queries.Datum
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, queries.Datum) (queries.Datum, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, queries.Datum) queries.Datum); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Get(0).(queries.Datum)
	}

	if rf, ok := ret.Get(1).(func(context.Context, queries.Datum) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
